// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5V5Ht0SK48hLfjdFwhmKOVMC_IJ0gXPM',
    appId: '1:542176913757:web:dc71fdc118bf78162060b4',
    messagingSenderId: '542176913757',
    projectId: 'todo-clean-arch-1f8bc',
    authDomain: 'todo-clean-arch-1f8bc.firebaseapp.com',
    storageBucket: 'todo-clean-arch-1f8bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtGxvqv4dvp9WckVMdrG4qOoswYkymKx8',
    appId: '1:542176913757:android:92fb299dec9f9ee12060b4',
    messagingSenderId: '542176913757',
    projectId: 'todo-clean-arch-1f8bc',
    storageBucket: 'todo-clean-arch-1f8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF4h90CTRN1W16sFJQ1Zv0mJKAXHjQPAg',
    appId: '1:542176913757:ios:49d99d14d77390b82060b4',
    messagingSenderId: '542176913757',
    projectId: 'todo-clean-arch-1f8bc',
    storageBucket: 'todo-clean-arch-1f8bc.appspot.com',
    iosBundleId: 'com.example.cp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF4h90CTRN1W16sFJQ1Zv0mJKAXHjQPAg',
    appId: '1:542176913757:ios:909580a8c2c12aea2060b4',
    messagingSenderId: '542176913757',
    projectId: 'todo-clean-arch-1f8bc',
    storageBucket: 'todo-clean-arch-1f8bc.appspot.com',
    iosBundleId: 'com.example.cp1.RunnerTests',
  );
}
